[general]
# Themes
# pick one from https://github.com/alacritty/alacritty-theme
import = [                                                      # type  | contrast |
  # "~/.config/alacritty/themes/github_dark_default.toml",      # dark  | low      |
  # "~/.config/alacritty/themes/github_dark_dimmed.toml",       # dark  | low      |
  # "~/.config/alacritty/themes/high_contrast.toml",            # dark  | high     |
  "~/.config/alacritty/themes/one_dark.toml",                 # dark  | average  | DEFAULT
  # "~/.config/alacritty/themes/solarized_dark.toml",           # dark  | low      |
  # "~/.config/alacritty/themes/github_light.toml",             # light | average  |
  # "~/.config/alacritty/themes/solarized_light.toml",          # light | low      |
]

[font]
# Point size: a gap can appear at the bottom of the emulator, depending on this value
# and the height of the emulator window
size = 9.0

[[hints.enabled]]
action = "Copy"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true

[window.padding]
# Blank space added around the window in pixels. This padding is not scaled
# by DPI and the specified value is always added at both opposing sides.
x = 4
y = 4
