people_dir: ~/people
ignore:
  - AinhoaGalarza
  - AlaisterDalgarno
  - AlbaVidalGarcia
  - AliHammamiTamayo
  - AnderCelaya
  - AnderLopezDeLetona
  - ArtemKim
  - BegoBayer
  - BorjaAlonso
  - BorjaSancho
  - CatherineHudson
  - ClaraNoviaAsierEgiluz
  - CraigGraw
  - DanBabylon
  - DanielDelReguerro
  - DanielIonita
  - Hannah
  - HelenaPonte
  - IgorHandicaps
  - IgorTelegram
  - IñakiGuerra
  - IñigoSalaburu
  - IreneTorralba
  - IvanArozamena
  - IvanElDeBisjueces
  - IzarMorenoPerez
  - IzasAmigaDeLaurita
  - JaviGomez
  - JoeBabylon
  - JonAnderDoctorVicho
  - JonGrandes
  - JuanCarlosTorralba
  - KarinaWegner
  - LauraCarrillo
  - LeoEscalada
  - LibeAguayo
  - LourdesMolinero
  - LucíaRiera
  - MariaIzagirre
  - MikelAretxabala
  - NereaGorostidi
  - PatriciaRuiz
  - PaulBerril
  - SaioaGoikoetxea
  - SofiaEsparcia
  - TaniaAlcaide
  - Udane
  - VanesaRiera
  - XabierMarañón
  - YanLau
