# Disable the newline at the start of the prompt
add_newline = false

[git_branch]
symbol = ""

[git_status]
conflicted = "CONFLICT"
ahead = "[⇡${count}](blue) "
behind = "[⇣${count}](blue) "
diverged = "[⇡${ahead_count} ⇣${behind_count}](blue)"
untracked = "${count}? "
modified = " ${count}m "
staged = "[${count}++](green) "
renamed = "${count}r "
deleted = "${count}✘ "

[kubernetes]
symbol = "⛵ "
style = "dim green"
disabled = true

[nodejs]
symbol = "🤖 "

[directory]
truncation_length = 80
truncate_to_repo = false

[time]
disabled = false
format = "[$time](#555555)"

[cmd_duration]
disabled = true

[hostname]
ssh_only = false
format = "[$hostname](dimmed) "
disabled = false

[memory_usage]
threshold = 1
format = 'm:[${ram_pct}]($style) '
symbol = ""
disabled = false
