abbr --add g 'git' # Use 'g' as git (you still can use 'git')
abbr --add gs 'git status -s'
abbr --add ga 'git add'
abbr --add gc 'git commit'
abbr --add gpl 'git pull'
abbr --add gps 'git push'
abbr --add gch 'git checkout'
abbr --add gb 'git branch'
abbr --add gl 'git log --oneline --graph --decorate --all'
abbr --add gf 'git fetch --all --prune'
abbr --add gr 'git remote'
abbr --add gchd 'git_delete_branch_and_checkout.py'
abbr --add gw 'git commit -am "WIP_UNDO_ME"'
abbr --add gco 'git_commit_from_branch_name'
