abbr --add g 'git' # Use 'g' as git (you still can use 'git')
abbr --add gs 'git status -s'
abbr --add ga 'git add'
abbr --add gc 'git commit'
abbr --add gpl 'git pull'
abbr --add gps 'git push'
abbr --add gch 'git checkout'
abbr --add gb 'git branch'
abbr --add gd 'git branch -D'
abbr --add gm 'git branch -m'
abbr --add gl 'git log --oneline --graph --decorate --branches'
abbr --add gr 'git reset HEAD~'
abbr --add gw 'git commit -am "WIP_UNDO_ME"'
abbr --add grc 'git rebase --continue'
abbr --add gra 'git rebase --abort'
