abbr --add v 'vcsh dotfiles'
abbr --add vs 'vcsh dotfiles status'
abbr --add vb 'vcsh dotfiles branch'
abbr --add vch 'vcsh dotfiles checkout'
abbr --add va 'vcsh dotfiles add'
abbr --add vc 'vcsh dotfiles commit'
abbr --add vf 'vcsh dotfiles fetch --all --prune'
abbr --add vps 'vcsh dotfiles push'
abbr --add vpl 'vcsh dotfiles pull'
abbr --add vl 'vcsh dotfiles log --oneline --all --graph --decorate'
